services:
  ocr-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./ocr_service.py:/app/ocr_service.py
    environment:
      - FLASK_ENV=development
      - PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=True
      - FLAGS_allocator_strategy=naive_best_fit
      - FLAGS_fraction_of_gpu_memory_to_use=0
    restart: unless-stopped
